<a href="https://colab.research.google.com/github/t-cool/Projects/blob/master/numpy_zeros_ones_full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
"""
zeros(サイズ): 全ての要素が0の多次元配列
ones(サイズ): 全ての要素が1の多次元配列
full(サイズ, 値): 全ての要素が値の多次元配列
"""

np_zeros_3 = np.zeros(3)

In [3]:
np_zeros_3

array([0., 0., 0.])

In [0]:
np_zeros_23 = np.zeros((2,3))

In [5]:
np_zeros_23

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
np_ones_3 = np.ones(3)

In [7]:
np_ones_3

array([1., 1., 1.])

In [8]:
np_ones_23 = np.ones((2,3))
np_ones_23

array([[1., 1., 1.],
       [1., 1., 1.]])

In [0]:
np_full23_5 = np.full((2,3), 5)

In [10]:
np_full23_5

array([[5, 5, 5],
       [5, 5, 5]])

In [0]:
np_full3_5 = np.full(3,5)

In [12]:
np_full3_5

array([5, 5, 5])