<a href="https://colab.research.google.com/github/t-cool/Projects/blob/master/numpy_arange_linspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
data1 = np.ones((3,2))

In [0]:
data1

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [0]:
data2 = np.zeros((2,3))
data2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
data3 = np.arange(5)
data3

array([0, 1, 2, 3, 4])

In [0]:
data4 = np.arange(1,7)
data4

array([1, 2, 3, 4, 5, 6])

In [0]:
data5 = np.linspace(1,2,6)
data5

array([1. , 1.2, 1.4, 1.6, 1.8, 2. ])